--
-- Plantaria - BBDD demo minima para defensa del TFG
-- Generada para incluir en GitHub solo estructura y datos representativos.
-- Motor objetivo: PostgreSQL + PostGIS.
--

BEGIN;

CREATE EXTENSION IF NOT EXISTS postgis;

DROP TABLE IF EXISTS public.app_events CASCADE;
DROP TABLE IF EXISTS public.moderation_flags CASCADE;
DROP TABLE IF EXISTS public.observations CASCADE;
DROP TABLE IF EXISTS public.plant_records CASCADE;
DROP TABLE IF EXISTS public.users CASCADE;

CREATE TABLE public.users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid uuid NOT NULL UNIQUE,
    handle varchar(16) NOT NULL UNIQUE,
    display_name varchar(120) NOT NULL,
    email varchar(255) NOT NULL UNIQUE,
    email_verified_at timestamp(0),
    password varchar(255) NOT NULL,
    photo_path varchar(255),
    country varchar(100) NOT NULL,
    province varchar(100),
    city varchar(100),
    default_lat numeric(10,7),
    default_lng numeric(10,7),
    birthdate date,
    role varchar(16) DEFAULT 'user' NOT NULL,
    status varchar(16) DEFAULT 'active' NOT NULL,
    last_login_at timestamp(0),
    last_known_lat numeric(10,7),
    last_known_lng numeric(10,7),
    remember_token varchar(100),
    created_at timestamp(0),
    updated_at timestamp(0),
    deleted_at timestamp(0)
);

CREATE TABLE public.plant_records (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid uuid NOT NULL UNIQUE,
    public_id varchar(26) NOT NULL UNIQUE,
    created_by_user_id bigint NOT NULL REFERENCES public.users(id),
    provisional_common_name varchar(120) NOT NULL,
    verified_common_name varchar(120),
    verified_scientific_name varchar(180),
    description text,
    primary_photo_path varchar(255) NOT NULL,
    plant_condition varchar(32) DEFAULT 'unknown' NOT NULL,
    verification_status varchar(16) DEFAULT 'pending' NOT NULL,
    verified_by_user_id bigint REFERENCES public.users(id),
    verified_at timestamp(0),
    latitude numeric(10,7) NOT NULL,
    longitude numeric(10,7) NOT NULL,
    latest_observation_at timestamp(0),
    created_at timestamp(0),
    updated_at timestamp(0),
    deleted_at timestamp(0)
);

CREATE TABLE public.observations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid uuid NOT NULL UNIQUE,
    public_id varchar(26) NOT NULL UNIQUE,
    plant_record_id bigint NOT NULL REFERENCES public.plant_records(id),
    author_user_id bigint NOT NULL REFERENCES public.users(id),
    photo_path varchar(255) NOT NULL,
    note text,
    plant_condition varchar(32) DEFAULT 'unknown' NOT NULL,
    latitude numeric(10,7) NOT NULL,
    longitude numeric(10,7) NOT NULL,
    source_type varchar(16) DEFAULT 'update' NOT NULL,
    observed_at timestamp(0) NOT NULL,
    created_at timestamp(0),
    updated_at timestamp(0)
);

CREATE TABLE public.moderation_flags (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid uuid NOT NULL UNIQUE,
    target_type varchar(24) DEFAULT 'record' NOT NULL,
    target_id bigint NOT NULL,
    created_by_user_id bigint NOT NULL REFERENCES public.users(id),
    reason text NOT NULL,
    status varchar(16) DEFAULT 'open' NOT NULL,
    resolved_by_user_id bigint REFERENCES public.users(id),
    resolved_at timestamp(0),
    created_at timestamp(0),
    updated_at timestamp(0)
);

CREATE TABLE public.app_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid uuid NOT NULL UNIQUE,
    event_type varchar(64) NOT NULL,
    user_id bigint REFERENCES public.users(id),
    role_snapshot varchar(16),
    plant_record_id bigint REFERENCES public.plant_records(id),
    search_query varchar(255),
    search_type varchar(32),
    metadata json,
    occurred_at timestamp(0) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_at timestamp(0) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX users_role_status_index
    ON public.users (role, status);

CREATE INDEX plant_records_verification_status_created_at_index
    ON public.plant_records (verification_status, created_at);

CREATE INDEX plant_records_latitude_longitude_index
    ON public.plant_records (latitude, longitude);

CREATE INDEX observations_plant_record_id_observed_at_index
    ON public.observations (plant_record_id, observed_at);

CREATE INDEX moderation_flags_target_type_target_id_index
    ON public.moderation_flags (target_type, target_id);

CREATE INDEX moderation_flags_status_created_at_index
    ON public.moderation_flags (status, created_at);

CREATE INDEX app_events_event_type_occurred_at_index
    ON public.app_events (event_type, occurred_at);

CREATE INDEX app_events_user_id_occurred_at_index
    ON public.app_events (user_id, occurred_at);

INSERT INTO public.users (
    id, uid, handle, display_name, email, email_verified_at, password,
    photo_path, country, province, city, default_lat, default_lng,
    birthdate, role, status, last_login_at, last_known_lat, last_known_lng,
    remember_token, created_at, updated_at, deleted_at
) VALUES
    (1, 'dff6c2d5-99c9-4128-980f-dcaedd0edbc3', 'plantaria_admin', 'Plantaria Admin', 'admin@plantaria.local', '2026-05-07 10:39:44', '$2y$12$53sxhIpN9ncl8lh.WC7wg.X00uLh/TgmwW6XuUcJz7NqBzJFPGfjG', NULL, 'Espana', 'Valencia', 'Valencia', NULL, NULL, NULL, 'admin', 'active', NULL, NULL, NULL, NULL, '2026-04-20 18:30:00', '2026-05-07 10:39:44', NULL),
    (2, '3db35752-cf4f-4c39-a561-766219d23ddc', 'plantaria_demo', 'Plantaria Demo', 'demo@plantaria.local', '2026-05-07 10:39:45', '$2y$12$ng.KhmGdsy0ZBLVY1zrA5uMtBr2lN..pbHzOWlYS1RUBhafZdfZdS', NULL, 'Espana', 'Barcelona', 'Barcelona', 41.3874000, 2.1686000, NULL, 'user', 'active', '2026-04-23 17:21:21', NULL, NULL, NULL, '2026-04-21 17:12:10', '2026-05-07 10:39:45', NULL),
    (3, '3fd8d073-6180-4057-b489-0be9d9d3f5ce', 'plantaria_user', 'Plantaria Usuario', 'user@plantaria.local', '2026-05-07 10:39:45', '$2y$12$v1VeeGZg5YeMlPCkztliNeao.yNxd1QkJxzrK0aJeYeHl2voVWT2G', NULL, 'Espana', 'Barcelona', 'Barcelona', 41.3874000, 2.1686000, NULL, 'user', 'active', NULL, NULL, NULL, NULL, '2026-04-28 14:46:12', '2026-05-07 10:39:45', NULL),
    (4, '2f76ffa6-0902-49b8-afca-f51e27f95bf4', 'plantaria_mod', 'Plantaria Moderador', 'mod@plantaria.local', '2026-05-07 10:39:45', '$2y$12$Md7KKeRcPWIMl4DWRvHc.eNg04JEM8L45CQ8v7Aonkrglxwdz7Yla', NULL, 'Espana', 'Barcelona', 'Barcelona', 41.3874000, 2.1686000, NULL, 'mod', 'active', NULL, NULL, NULL, NULL, '2026-04-28 14:46:12', '2026-05-07 10:39:45', NULL);

INSERT INTO public.plant_records (
    id, uid, public_id, created_by_user_id, provisional_common_name,
    verified_common_name, verified_scientific_name, description,
    primary_photo_path, plant_condition, verification_status,
    verified_by_user_id, verified_at, latitude, longitude,
    latest_observation_at, created_at, updated_at, deleted_at
) VALUES
    (1, 'c07122dd-09db-4f41-9d9c-b9a19f766f9e', 'PLANTARIADEMOBCN000001', 2, 'Platanero', 'Platanero de sombra', 'Platanus x hispanica', 'Ejemplar urbano junto al Parc de la Ciutadella.', 'demo/platanero-ciutadella.png', 'good', 'verified', 1, '2026-05-06 12:39:45', 41.3887900, 2.1871200, '2026-05-06 10:39:45', '2026-04-21 17:12:10', '2026-05-07 10:39:45', NULL),
    (2, '1ae9e651-650a-4b79-a834-f14b1f60ab20', 'PLANTARIADEMOBCN000002', 2, 'Lavanda', 'Lavanda', 'Lavandula angustifolia', 'Mata aromatica en zona ajardinada de Montjuic.', 'demo/lavanda-montjuic.png', 'good', 'verified', 1, '2026-05-05 12:39:45', 41.3635500, 2.1576600, '2026-05-05 10:39:45', '2026-04-21 17:12:10', '2026-05-07 10:39:45', NULL),
    (3, '699ad9e7-18d1-43ee-add3-48ceb9f13ee2', 'PLANTARIADEMOBCN000003', 2, 'Romero', 'Romero', 'Salvia rosmarinus', 'Arbusto mediterraneo cerca del Park Guell.', 'demo/romero-park-guell.png', 'regular', 'verified', 1, '2026-05-04 12:39:45', 41.4144900, 2.1526900, '2026-05-04 10:39:45', '2026-04-21 17:12:10', '2026-05-07 10:39:45', NULL),
    (4, 'a4202f71-11e7-404f-8ee7-6c333fe557d1', 'PLANTARIADEMOBCN000004', 2, 'Bugambilia', NULL, NULL, 'Registro pendiente de moderacion en Gracia.', 'demo/bugambilia-gracia.png', 'unknown', 'pending', NULL, NULL, 41.4026900, 2.1595200, '2026-05-07 02:39:45', '2026-04-21 17:12:10', '2026-05-07 10:39:45', NULL);

INSERT INTO public.observations (
    id, uid, public_id, plant_record_id, author_user_id, photo_path,
    note, plant_condition, latitude, longitude, source_type,
    observed_at, created_at, updated_at
) VALUES
    (1, 'c2ae1ef4-69ed-403b-9096-1fc8e5d2f882', 'OBSDEMOBCN000001', 1, 2, 'demo/platanero-ciutadella.png', 'Ejemplar urbano junto al Parc de la Ciutadella.', 'good', 41.3887900, 2.1871200, 'initial', '2026-05-06 10:39:45', '2026-04-21 17:12:10', '2026-05-07 10:39:45'),
    (2, 'c755eb3d-e28d-4213-a098-832b2c29298c', 'OBSDEMOBCN000002', 2, 2, 'demo/lavanda-montjuic.png', 'Mata aromatica en zona ajardinada de Montjuic.', 'good', 41.3635500, 2.1576600, 'initial', '2026-05-05 10:39:45', '2026-04-21 17:12:10', '2026-05-07 10:39:45'),
    (3, '61325984-529d-41da-87a9-b25face25010', 'OBSDEMOBCN000003', 3, 2, 'demo/romero-park-guell.png', 'Arbusto mediterraneo cerca del Park Guell.', 'regular', 41.4144900, 2.1526900, 'initial', '2026-05-04 10:39:45', '2026-04-21 17:12:10', '2026-05-07 10:39:45'),
    (4, '8514f09e-c1ad-49f8-b45c-76b6a65ccee3', 'OBSDEMOBCN000004', 4, 2, 'demo/bugambilia-gracia.png', 'Registro pendiente de moderacion en Gracia.', 'unknown', 41.4026900, 2.1595200, 'initial', '2026-05-07 02:39:45', '2026-04-21 17:12:10', '2026-05-07 10:39:45');

SELECT setval(pg_get_serial_sequence('public.users', 'id'), 4, true);
SELECT setval(pg_get_serial_sequence('public.plant_records', 'id'), 4, true);
SELECT setval(pg_get_serial_sequence('public.observations', 'id'), 4, true);
SELECT setval(pg_get_serial_sequence('public.moderation_flags', 'id'), 1, false);
SELECT setval(pg_get_serial_sequence('public.app_events', 'id'), 1, false);

COMMIT;
